apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocoding-service
spec:
  selector:
    matchLabels:
      app: geocoding-service
  template:
    metadata:
      labels:
        app: geocoding-service
    spec:
      containers:
      - image: geocoding-service/grc.io:latest
        name: app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: geocoding-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: geocoding-service