apiVersion: apps/v1
kind: Deployment
metadata:
  name: __serviceName__
  namespace: __nameSpace__
  labels:
    app: geocoding-service
    version: __version__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: __serviceName__
  template:
    metadata:
      labels:
        app: __serviceName__
    spec:
      containers:
        - name: __serviceName__
          imagePullPolicy: Always
          image: gcr.io/__projectId__/__serviceName__:__version__
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          ports:
            - containerPort: __port__
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
              ephemeral-storage: "1Gi"
            limits:
              cpu: 200m
              memory: 2048Mi
              ephemeral-storage: "2Gi"
          volumeMounts:
            - mountPath: /var/log/containers/
              name: varlog

        - name: __serviceName__-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -f /var/log/containers/__serviceName__.log']
          volumeMounts:
            - mountPath: /var/log/containers/
              name: varlog

      volumes:
        - hostPath:
            path: /var/log/containers/
            type: ""
          name: varlog

---
kind: Service
apiVersion: v1
metadata:
  name: __serviceName__
  namespace: __nameSpace__
  labels:
    app: geocoding-service
spec:
  type: ClusterIP
  selector:
    app: __serviceName__
  ports:
  - name: http
    port: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: __serviceName__
  namespace: __nameSpace__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  __serviceName__
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
